export const API_ROUTES = {
  REGISTER_USER: "/auths/signup",
  LOGIN: "/auths/login",
  FETCH_BUSINESSES: "/businesses/",
  GET_BUSINESS: (id: string) => `/businesses/${id}`,
  UPDATE_BUSINESS: (id: string) => `/businesses/${id}`,
  FETCH_LAUNDRY_SERVICES: "/laundry-services/",
  FETCH_DRIVERS: "/drivers",
  FETCH_ORDERS: "/orders",
  CREATE_ORDER: "/orders/",
  UPDATE_ORDER_STATUS: (order_id: string) => `/orders/${order_id}/status`,
  UPDATE_ORDER_PRICING: (order_id: string) => `/orders/${order_id}/pricing`,
  APPROVE_DRIVER: (id: string) => `/drivers/${id}/approve`,
  REJECT_DRIVER: (id: string) => `/drivers/${id}/reject`,
  GET_DRIVER: (id: string) => `/drivers/${id}`,
  UPDATE_DRIVER: (id: string) => `/drivers/${id}`,
  SUSPEND_DRIVER: (id: string) => `/drivers/${id}/suspend`,
  CREATE_BUSINESS: "/businesses/",
  DELETE_BUSINESS: (business_id: string) => `/businesses/${business_id}`,
  CREATE_BUSINESS_SERVICES: "/business-services/bulk",
};
